### ISSUE TITLE
reference bar option for facet bar chart?

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#16]
This would be helpful for visualizations with more than 2 dimensions - example would be homeownership by race and income

**Comment by jensenmj** [comment]
It looks like Christy already handled this with her facet chart update--the chart generated from her example code looks good! @cyyllam , can you confirm and close?

**Comment by cyyllam** [comment]
Issue resolved with latest `static_facet_column_chart()` update
