### ISSUE TITLE
redo the facet_chart function with all updates to be like the other functions

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrcplot#17]
it's ggiraph; w.x, and parameters need to change, reference lines need to be added

update first for static facet charts; then

**Comment by cyyllam** [comment]
created `static_facet_column_chart()` in lieu of `create_...()`

- standardized parameter names 
- added 1 reference line option
-  dynamic x-axis labeling if `x` and `fill` arguments are different
- Not interactive
