### ISSUE TITLE
Error bars not showing when exceeding limits

### ISSUE THREAD

**Issue by Joanneylin** [psrc/psrcplot#29]
The error bars are incomplete when the upper or lower bound values exceeded the limits of the plot. 

Maybe use an aggregation of `.data[[y]+.data[[moe]]` to determine max_item?

```
telecommute_times_per_week_chart <- static_column_chart(t = telecommute_times_per_week,
                                                        x = "telecommute_freq", y = "share",
                                                        fill = "survey",
                                                        moe = "share_moe",
                                                        color = "pgnobgy_5",
                                                        title = "Telecommute Frequency: Times per Week")
```

<img width="428" alt="image2" src="https://user-images.githubusercontent.com/71201494/213020435-b9a5c894-7221-4f14-a7f2-b52ae74f213f.png">

**Comment by jensenmj** [comment]
@Joanneylin , would you please update the package and re-run this code to verify it's still a problem? I think I've addressed it, but don't have high-moe data at hand to test it. If it's solved, please close. 8^)
