### ISSUE TITLE
Way to reverse order of categories in code?

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#3]
I would like to reverse the racial category labels so that the order is alphabetical from top to bottom. When I use the create_bar_chart function with coord_flip(), the output is:
![image](https://user-images.githubusercontent.com/72169299/190219990-e8b0db46-37eb-4dae-af59-f22e14c11607.png)

When I create it manually (without the PSRC preset template fonts/colors), I am able to reverse the order within the code:
![median income by race](https://user-images.githubusercontent.com/72169299/190220478-ea9f5ff4-733f-43af-b180-05cfab7a53f7.png)

**Comment by Ennazus** [comment]
We should provide an example of how to do this in FAQs

**Comment by MrichardsPSRC** [comment]
@Ennazus - Where are the FAQs for this package?
