### ISSUE TITLE
Warning message: "font family not found in Windows font database"

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#4]
This is new today - I wasn't encountering this yesterday. I have tried to re-install, but not sure what changed in the last day.

When using the create_bar_chart function, I am encountering this error message:
![image](https://user-images.githubusercontent.com/72169299/190222904-99215b94-e60c-4750-a4da-b0f7a0df1c17.png)

The code still produces the desired chart (ignoring the previous issue I posted about category order):
![image](https://user-images.githubusercontent.com/72169299/190223194-d25ecd08-fb53-45dc-83c7-cbc0b32b70eb.png)

**Comment by MrichardsPSRC** [comment]
Here is the code to set up the dataset - I can provide a link to the code as well:
![image](https://user-images.githubusercontent.com/72169299/190223417-09d933d7-5292-4899-a1f2-be3985d87557.png)

**Comment by Ennazus** [comment]
Add documentation on how to have fonts loaded
