### ISSUE TITLE
Static_line_chart - x/y labels

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#44]
I am creating a static line chart and have a few questions about the x/y axis labels.

```
line_option <- static_line_chart(t=lifeexpec_poc_trend,
                                 x="year", y="health_ind",
                                 fill="quintile_order",
                                 est = "number",
                                 color = "blues_inc",
                                 title = indicator_measure,
                                 subtitle = "People of Color",
                                 source = paste("Sources: Washington Tracking Network, Washington State Department of Health,", "\n", "U.S. Census Bureau, PUMS 1-year, 2015-2020,", "\n", "2020 Census Tracts"))
```

![image](https://user-images.githubusercontent.com/72169299/215932356-2c54759b-3e46-4c1e-9c1d-c5accbd3573a.png)

1. Is there a way to remove the x and y axis labels and/or edit them? Similar to the column and bar charts where xlabel and ylabel are options, but defaulted to NULL? 

2. Is there a way to provide the years along the x-axis? Since line charts are often used to look at data over time, I'm not sure if this should be a default or not? I saw that one of the arguments included the generic line function is dform, which I would want to be set as %Y. The "year" field is numeric, but I could set it as Date type...

```
lifeexpec_poc_trend$year_date <- as.Date((as.character(lifeexpec_poc_trend$year)),
                                         format = "%Y")
```

But using this new field in the line chart function returns an error, with or without the dform commented out

```
line_option <- static_line_chart(t=lifeexpec_poc_trend,
                                 x="year_date", y="health_ind",
                                 fill="quintile_order",
                                 est = "number",
                                 # dform = "%Y",
                                 color = "blues_inc",
                                 title = indicator_measure,
                                 subtitle = "People of Color",
                                 source = paste("Sources: Washington Tracking Network, Washington State Department of Health,", "\n", "U.S. Census Bureau, PUMS 1-year, 2015-2020,", "\n", "2020 Census Tracts"))
```

![image](https://user-images.githubusercontent.com/72169299/215933338-a42262a6-0dc1-4227-adef-90d743b6be0d.png)

Would be happy for any advice about this - is it necessary to make it a Date field? Am I missing something simple in my functions?

**Comment by jensenmj** [comment]
Fixed with commit c9a685c.
