### ISSUE TITLE
interactive chart legend should be on bottom

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrcplot#60]

**Comment by cyyllam** [comment]
Is there an example chart where it would be optimal to be on the bottom? I made some changes to `make_interactive()` in the event there's a lot of x categories the labels would pivot 90 degrees and the legend be on the top right so not to block anything
![image](https://user-images.githubusercontent.com/17414750/217625583-71afb12d-ba4f-4df8-aaba-87ca367c79b4.png)

**Comment by Ennazus** [comment]
Thanks Christy! I'll figure something out...

**Comment by Ennazus** [comment]
For now we'll just put the labels at the bottom, and handle the case of rotation later. this accomodates the RTP dashboard better

**Comment by jensenmj** [comment]
If this no longer requires any action, we should close it.
