### ISSUE TITLE
interactive chart not allowing date for x-axis

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrcplot#61]
we thought it was closed. maybe were doing something wrong?

**Comment by Ennazus** [comment]
the issue can be seen on the vehicle registration dashbaord

**Comment by Ennazus** [comment]
to be fixed in 1.1 - for 1.0 - handle on the data prep side (with like mutates)

**Comment by jensenmj** [comment]
Solved with commit 43b0e78.

**Comment by jensenmj** [comment]
Solved with c321c53
