### ISSUE TITLE
Title cutting off for interactive charts dependent on height - include in documentation?

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#67]
In making an interactive column chart (**ignore the bad visualization**):

![image](https://user-images.githubusercontent.com/72169299/218171831-535201d5-4f18-403d-a6b3-665c22743e7a.png)

When I open it in a new window, the title disappears completely:
![image](https://user-images.githubusercontent.com/72169299/218172184-73b39c29-7c63-4bec-9cf5-ff518f306bfe.png)

When I try to save it it defaults to this:
![image](https://user-images.githubusercontent.com/72169299/218172403-764fa26a-9fbe-4d59-8e01-c2d266aebc1d.png)

After playing around with the dimensions, it improves. It seems that its dependent on the height which needs to be **less than 425** for this particular plot (I can try running this for other charts and test different dimensions)? This may be useful to include in documentation?
![image](https://user-images.githubusercontent.com/72169299/218172496-93dc7361-35f3-4849-9fae-67250b7124e1.png)

![image](https://user-images.githubusercontent.com/72169299/218172886-5db9b10f-b69f-4879-87be-53c377488552.png)

![image](https://user-images.githubusercontent.com/72169299/218172950-7974015f-bcd9-422b-a17d-e516461dc5e8.png)

![image](https://user-images.githubusercontent.com/72169299/218173015-22fc083f-4481-4236-bf42-80375e876e0b.png)

![image](https://user-images.githubusercontent.com/72169299/218172600-be2481fa-31ee-4dbe-8d09-6ed87fc988d3.png)

**Comment by Ennazus** [comment]
We're leaning towards putting the titles outside of the charts because plotly is difficult for aligning the titles correctly

**Comment by jensenmj** [comment]
Mentioned in customization page, commit #e224253. We may still want to address this later, but considering done for now.
