### ISSUE TITLE
Reference values in documentation

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#68]
I'm trying to include reference values and it would be useful to see an example of how the dataset should be formatted to be able to include reference values - this could be in FAQs or the first few lines of the dataset used in this example could be printed in the example section:

![image](https://user-images.githubusercontent.com/72169299/218179525-f66d443e-1225-4c9a-91fa-4a9e6d0b3327.png)
(https://psrc.github.io/psrcplot/reference/static_facet_column_chart.html) 

Here are two possible ways that I could set up the data to have the regional number as a reference - the first as an additional row, the second as a reference column:
![image](https://user-images.githubusercontent.com/72169299/218180946-a281ff75-161a-4891-8fe2-e9e820541bdd.png)

![image](https://user-images.githubusercontent.com/72169299/218182197-72a00c79-d0b1-42e9-9fc0-fc3acc63b1f3.png)

When the dataset is set up like the second image,
```
# generate static bar chart
own_race_chart <- static_bar_chart(t=dt_2021,
                                   x="share", y="HRACE",
                                   fill="HRACE",
                                   pos="dodge",
                                   est="percent",
                                   # moe="share_moe",
                                   href=ref_val, hrefnm="Region",
                                   hrefcl='#00716c',
                                   title="Homeownership by Race and Hispanic/Latinx Origin",
                                   subtitle=NULL,
                                   source="2021 American Commmunity Survey 1-year Data",
                                   alt=NULL,
                                   xlabel=NULL, ylabel=NULL,
                                   dec = 2, color="psrc_light") + theme(legend.position = "none") + scale_x_discrete(limits=rev) #flip order
```
![image](https://user-images.githubusercontent.com/72169299/218184774-3db142ed-960a-4c04-9314-2e8f741cdec4.png)

If I manually do it I can rearrange the label so it's not overlapping with the numbers in the chart: 
```
# trying to figure out reference line - static
test_static <- own_race_chart + 
  ggplot2::geom_hline(yintercept= ref_val,
                      linetype='solid', linewidth=2, show.legend = FALSE, color='#00716c') +
  ggplot2::annotate("text", x = 1, y = ref_val+0.02, label = "Region", angle='270', color='#00716c')
```
![image](https://user-images.githubusercontent.com/72169299/218185035-2a87bd0c-c7e9-4f4c-a4c1-517262d02679.png)

**Comment by Ennazus** [comment]
longer term find a better solution

**Comment by jensenmj** [comment]
Handled/made obsolete via commit #4a562d5. Example now in the FAQ vignette.
