### ISSUE TITLE
Update vignette re: wrapping x-axis labels

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#69]
https://psrc.github.io/psrcplot/articles/frequently-asked-questions.html#how-can-i-wrap-the-text-on-a-column-chart-x-axis--its-looking-messy

I think that the first screenshots under this section is incorrect since it's already fixed with wrapping?
![image](https://user-images.githubusercontent.com/72169299/218189134-a5401e76-7960-4975-9edd-d1a585c8a68c.png)

When it should look more like this:
![image](https://user-images.githubusercontent.com/72169299/218189385-f3a0b343-f943-49cc-ab14-8b17755ea531.png)

When I incorporate the text wrapping code, like provided in the example, it works well but the text is oriented horizontally (left-right), not like the text in the example screenshot which is oriented veritcally (bottom-top): 
![image](https://user-images.githubusercontent.com/72169299/218190061-1b57d5d8-872f-47fd-b73f-8a1668580469.png)

```
# generate static column chart
xlabs <- levels(dt_2021_simprace$HRACE) %>% stringr::str_wrap(12)

own_race_chart <- static_column_chart(t=dt_2021_simprace, 
                                   x="HRACE", y="HINCP_median", 
                                   fill="HRACE",
                                   pos="dodge",
                                   est="currency",
                                   # moe="HINCP_median_moe",
                                   # href="ref_val", hrefnm="Region",
                                   # hrefcl='#00716c',
                                   title="Regional Household Median Income by Race and Hispanic/Latinx Origin",
                                   subtitle=NULL, 
                                   source="2021 American Commmunity Survey 1-year data",
                                   alt=NULL,
                                   xlabel=NULL, ylabel=NULL,
                                   dec = 0, color="psrc_light") + theme(legend.position = "none") +
  ggplot2::scale_x_discrete(labels=xlabs) #+ scale_x_discrete(limits=rev) #alphabetical order
```
![image](https://user-images.githubusercontent.com/72169299/218189700-76d2a0e1-b965-437e-a023-8e041ba9166d.png)

I'm not sure if the screenshot should be updated or if I am missing something? Also not sure if it would be beneficial to include a note on how to orient the text vertically or horizontally? Based on my output it seems that the default it horizontal.

**Comment by jensenmj** [comment]
Solved with commit #e224253.
