### ISSUE TITLE
Keep display plot dimensions in saved object (e.g. png)

### ISSUE THREAD

**Issue by MrichardsPSRC** [psrc/psrcplot#73]
I'm trying to save a png using the example code here (https://psrc.github.io/psrcplot/articles/make-plots.html#exporting-a-static-chart):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/72169299/219781909-689aadc4-ecce-41a4-95c0-67d8190bb04e.png)

The dimensions look strange (because the default is 7x7?) and I'd prefer it to look like the chart when I render it in R:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/72169299/219782086-753fc5f4-7bff-4299-9518-82987c04672a.png)

I manually set the height=3.5 and width=5 and it looks ok but still not as nice as the default R plot:
![image](https://user-images.githubusercontent.com/72169299/219783455-744a37fd-f96f-453d-95b6-764a26bf54c9.png)

**Comment by cyyllam** [comment]
Following their instructions: [](https://www.njtierney.com/post/2018/02/28/three-r-tips/) (tip #1: save the images that you create in Rmarkdown)

- In the yaml, include the `keep_md: yes` option.
- When you knit, it'll create a nested folder that keeps all the saved images.
- The saved image looks like how it appears in Rmarkdown.
