### ISSUE TITLE
test making a facet chart interactive

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrcplot#76]

**Comment by MrichardsPSRC** [comment]
I tried using some existing code:

```
lower_lim <- 75
upper_lim <- 85

healthrisk_quintile_facet<- static_facet_column_chart(t=healthrisk_equity_order,
                                                      x="quintile_order", y="wgt_health_risk_score",
                                                      fill="quintile_order", facet="aggregation",
                                                      color="blues_inc",
                                                      est ="number",
                                                      dec=2,
                                                      scales="fixed",
                                                      ncol=3,
                                                      title=indicator_measure,
                                                      subtitle = "by equity quintiles",
                                                      source=paste("Sources: Washington Tracking Network, Washington State Department of Health,", "\n", "U.S. Census Bureau, American Community Survey (ACS) 2021 1-Year Estimates,", "\n", "2020 Census Tracts")) + coord_cartesian(ylim = c(lower_lim, upper_lim)) 
```

![image](https://user-images.githubusercontent.com/72169299/222292310-1ed05de6-e96c-456f-b491-1036f34efad5.png)


changing it to ploty:

```
test_plotly <- ggplotly(healthrisk_quintile_facet_test)
```

![image](https://user-images.githubusercontent.com/72169299/222292490-b8b401f7-17fb-46a2-9556-8596ceceec73.png)

**Comment by MrichardsPSRC** [comment]
I think that its been discussed but turning a ggplot object to a plotly object removes a lot of the features and adds additional ones, like removing the subtitle and source, adding a legend. Making this into a function in psrcplot would require dealing with the legend and the hover information.

**Comment by MrichardsPSRC** [comment]
This feature may not be necessary for final production. We are using the facet charts to do exploratory visuzalizations, but if ggplot makes it difficult to create an interactive version and converting to ggiraph() is the best option, it may not be worth it to lose the consistency across the different chart types.
