### ISSUE TITLE
Line chart: bottom line/dot is cut off

### ISSUE THREAD

**Issue by ericclute** [psrc/psrcplot#84]
When generating this line chart, the lowest line/dot (in this case representing "$100,000 or more") is partially cut off by the X axis. It would be nice if there was a small out of space here so the user could completely see the line/dot. 

`years <- c(2010, 2016, 2021)

rcb_inc_func <- function(year){
  
  # Pull PUMS data
  setwd("C:/Users/eclute/Downloads")
  rcb_raw <- get_psrc_pums(5,year,"h",c("PRACE","TEN","GRPIP","HINCP"))
  setwd("J:/Projects/V2050/Housing/Monitoring/2023Update")
  rcb <- rcb_raw
  
  # Adjust for inflation
  rcb <- real_dollars(rcb, 2021)
  
  # Filter to only renters, create income/rent burden groupings, rename race/ethnicity categories, combine Some other Race & Two or More Races
  rcb <- rcb %>% filter(TEN=="Rented") %>%
    mutate(
      income_bin=factor(case_when(HINCP2021 < 25000 ~ "Under $25,000",
                                  HINCP2021 < 35000 ~ "$25,000-$34,999",
                                  HINCP2021 < 50000 ~ "$35,000-$49,999",
                                  HINCP2021 < 75000 ~ "$50,000-$74,999",
                                  HINCP2021 < 100000 ~ "$75,000-$99,999",
                                  HINCP2021 >=100000 ~ "$100,000 or more",
                                  !is.na(HINCP2021) ~ "Else / Prefer not to answer"),
                        levels=c("Under $25,000",
                                 "$25,000-$34,999",                                     
                                 "$35,000-$49,999",
                                 "$50,000-$74,999",
                                 "$75,000-$99,999",
                                 "$100,000 or more",
                                 "Else / Prefer not to answer")),
      rent_burden=factor(case_when(GRPIP < 30 ~"Less than 30 percent",
                                   between(GRPIP,30,50) ~ "Between 30 and 50 percent",
                                   GRPIP > 50 ~ "Greater than 50 percent",
                                   !is.na(GRPIP) ~ "No rent paid"),
                         levels=c("Greater than 50 percent",
                                  "Between 30 and 50 percent",
                                  "Less than 30 percent",
                                  "No rent paid")))
  
  # Summarize
  rcb_inc <- psrc_pums_count(rcb, group_vars = c("income_bin","rent_burden"),rr=TRUE)
  rcb_inc <- rcb_inc %>% pivot_wider(names_from = rent_burden, values_from = c(count, count_moe, share, share_moe, reliability))
  
  # Clean table
  rcb_inc <- rcb_inc[, c(1,3,4,5,6,8,7,9,10,11,13,12,14,15,16,18,17,24,25,26,28,27)]
  rcb_inc <- rcb_inc[rcb_inc$income_bin !='Total',]
  
  # Clean variable names
  rcb_inc <- rcb_inc %>% rename_all(~stringr::str_replace_all(.,"count_",""))
  rcb_inc <- rcb_inc %>% rename("No rent paid" = "NA")
  rcb_inc <- rcb_inc %>% rename("moe_No rent paid" = "moe_NA")
  rcb_inc <- rcb_inc %>% rename("Share_No rent paid" = "share_NA")
  rcb_inc <- rcb_inc %>% rename("Reliability_No rent paid" = "reliability_NA")

}

# Run rcb function
rcb_inc_all <- map(years, ~rcb_inc_func(.x)) %>%
  reduce(bind_rows)

# graph change over time 
library(psrcplot)
library(ggplot2)

rcb_inc_cb <- static_line_chart(rcb_inc_all_chart, "DATA_YEAR", "share_Between 30 and 50 percent", fill = "income_bin",
                                   title="Change in Cost Burden by Income (30-50% of income)",color="pgnobgy_10")
rcb_inc_cb`

**Comment by ericclute** [comment]
Example chart
![image](https://github.com/psrc/psrcplot/assets/101210389/6ea7660a-ac2e-44f4-9573-272495bc8855)

**Comment by Ennazus** [comment]
overhaul with echarts, may not be a problem
